<?php
$c = mysqli_connect("srv25.cpanelhost.cl","cre95340_admin","Vaips*2026","cre95340_erp");
mysqli_set_charset($c,"utf8mb4");
$excl = array_flip(array_filter(array_map('trim', explode("\n", file_get_contents("/tmp/e2.txt")))));

function pgtype($ct, $extra, &$pre, $tabla, $col, $c) {
  $base = trim(str_replace('unsigned','',preg_replace('/\(.*/','',$ct)));
  if (preg_match('/^enum\((.*)\)$/i', $ct, $m)) {
    $vals = str_getcsv($m[1], ',', "'");
    $r = mysqli_query($c, "SELECT COUNT(*) n FROM `$tabla` WHERE `$col`=''");
    $x = $r ? mysqli_fetch_assoc($r) : ['n'=>0];
    if ($x['n'] > 0) $vals[] = '';
    $vals = array_values(array_unique($vals));          // MySQL admite etiquetas repetidas; PostgreSQL no
    $tn = strtolower($tabla."_".$col."_enum");
    $pre[] = "CREATE TYPE $tn AS ENUM (".implode(', ', array_map(fn($v)=>"'".str_replace("'","''",$v)."'", $vals)).");";
    return $tn;
  }
  if (preg_match('/^decimal\(([\d,]+)\)/i',$ct,$m)) return "numeric($m[1])";
  if (preg_match('/^(varchar|char)\((\d+)\)/i',$ct,$m)) return strtolower($m[1])."($m[2])";
  return match($base) {
    'int','mediumint' => 'integer', 'bigint' => 'bigint',
    'smallint','tinyint' => 'smallint',
    'double' => 'double precision', 'float' => 'real',
    'text','mediumtext','longtext','tinytext' => 'text',
    'date' => 'date', 'datetime','timestamp' => 'timestamp', 'time' => 'time',
    'year' => 'smallint', 'blob','mediumblob','longblob' => 'bytea',
    default => 'text',
  };
}

$r = mysqli_query($c,"SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_type='BASE TABLE' ORDER BY table_name");
$tablas = [];
while($x = mysqli_fetch_assoc($r)) if(!isset($excl[$x['table_name']])) $tablas[] = $x['table_name'];

$pre = []; $body = []; $descartados = [];
foreach ($tablas as $t) {
  $cols = []; $pk = [];
  $r = mysqli_query($c,"SELECT column_name,column_type,is_nullable,column_default,extra FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='$t' ORDER BY ordinal_position");
  while($x = mysqli_fetch_assoc($r)) {
    $tp = pgtype($x['column_type'], $x['extra'], $pre, $t, $x['column_name'], $c);
    $line = '  "'.$x['column_name'].'" '.$tp;
    if (str_contains($x['extra'],'auto_increment')) $line .= ' GENERATED BY DEFAULT AS IDENTITY';
    elseif ($x['column_default'] !== null) {
      $d = $x['column_default'];
      $lit = (strlen($d) > 1 && $d[0] === "'" && substr($d,-1) === "'");
      if ($lit) $d = substr($d, 1, -1);                  // MariaDB devuelve los literales entrecomillados
      if (preg_match('/^0000-00-00/', $d) || strtoupper($d) === 'NULL') {
        $descartados[] = "$t.".$x['column_name']." (default invalido '$d')"; $d = null;
      } elseif (!$lit && preg_match('/current_timestamp/i', $d)) $d = 'CURRENT_TIMESTAMP';
      elseif ($lit || !is_numeric($d)) $d = "'".str_replace("'","''",$d)."'";
      if ($d !== null) $line .= " DEFAULT $d";
    }
    if ($x['is_nullable'] === 'NO') $line .= ' NOT NULL';
    $cols[] = $line;
  }
  $r = mysqli_query($c,"SELECT column_name FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='$t' AND index_name='PRIMARY' ORDER BY seq_in_index");
  while($x = mysqli_fetch_assoc($r)) $pk[] = '"'.$x['column_name'].'"';
  if ($pk) $cols[] = '  PRIMARY KEY ('.implode(', ',$pk).')';
  $body[] = "CREATE TABLE \"$t\" (\n".implode(",\n",$cols)."\n);";
}

$idx = [];
foreach ($tablas as $t) {
  $r = mysqli_query($c,"SELECT index_name,non_unique,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='$t' AND index_name<>'PRIMARY' GROUP BY index_name,non_unique");
  while($x = mysqli_fetch_assoc($r)) {
    $cl = implode(', ', array_map(fn($v)=>'"'.$v.'"', explode(',',$x['cols'])));
    $idx[] = "CREATE ".($x['non_unique']=='0'?'UNIQUE ':'')."INDEX \"".$t."_".$x['index_name']."\" ON \"$t\" ($cl);";
  }
}

echo "-- Replica ERP VAIPS -> PostgreSQL\n-- Generado desde information_schema de cre95340_erp\n";
echo "-- ".count($tablas)." tablas, ".count($pre)." tipos enum, ".count($idx)." indices\n";
foreach ($descartados as $d) echo "-- default descartado: $d\n";
echo "\n".implode("\n",$pre)."\n\n".implode("\n\n",$body)."\n\n".implode("\n",$idx)."\n";
